### ISSUE TITLE
Error when trying to login

### ISSUE THREAD

**Issue by Yukino-Kitsune** [seanwlk/wfaccountmanager#3]
```
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\pythonProject\wf_parser.py", line 7, in <module>
    wf.login('mail@mail.ru', 'password')
  File "C:\Users\Admin\PycharmProjects\pythonProject\venv\lib\site-packages\wfaccountmanager\__init__.py", line 289, in login
    return _russia(account,password)
  File "C:\Users\Admin\PycharmProjects\pythonProject\venv\lib\site-packages\wfaccountmanager\__init__.py", line 156, in _russia
    r = self.session.post("https://auth.mail.ru/cgi-bin/auth",headers=payload,data=data)
  File "C:\Users\Admin\PycharmProjects\pythonProject\venv\lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "C:\Users\Admin\PycharmProjects\pythonProject\venv\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "C:\Users\Admin\PycharmProjects\pythonProject\venv\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "C:\Users\Admin\PycharmProjects\pythonProject\venv\lib\site-packages\requests\models.py", line 369, in prepare
    self.prepare_headers(headers)
  File "C:\Users\Admin\PycharmProjects\pythonProject\venv\lib\site-packages\requests\models.py", line 491, in prepare_headers
    check_header_validity(header)
  File "C:\Users\Admin\PycharmProjects\pythonProject\venv\lib\site-packages\requests\utils.py", line 1043, in check_header_validity
    _validate_header_part(value, "value", HEADER_VALIDATORS[type(value)][1])
  File "C:\Users\Admin\PycharmProjects\pythonProject\venv\lib\site-packages\requests\utils.py", line 1048, in _validate_header_part
    raise InvalidHeader(
requests.exceptions.InvalidHeader: Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: "https://o2.mail.ru/xlogin?authid=kc6q10mp.x56&client_id=bbddb88d19b84a62aedd1ffbc71af201&force_us=1&from=o2&logo_target=_none&no_biz=1&redirect_uri=https%3A%2F%2Fauth-ac.my.games%2Fsocial%2Fmailru_callback%2F&remind_target=_self&response_type=code&scope=&signup_target=_self&state=egouaLY1hDII9sXXAfoXbbhUlCIlyOTanFldZkyVbqYDKXLxEKwWwOzYnVbcHDdA';\n\t\t\t\tvar blocked =0;\n\t\t\t\tvar captcha =0;</script><script>\n\t\t\t\t(function (l, re, m) {\n\t\t\t\t\tblocked "
```

**Comment by seanwlk** [comment]
Hello, can you `pip install -U git+https://github.com/seanwlk/wfaccountmanager` and tell me if it works now? You can check the updates here: https://github.com/seanwlk/wfaccountmanager/commit/12b3b13c33ef32f986bfaa47b272943416dd27df
Mail ru changed the login endpoints and some payload options. If you confirm it's working for you i will push it on pypi with a new release

**Comment by Yukino-Kitsune** [comment]
Now its working. Thanks!
