### ISSUE TITLE
problem with Russian authorization

### ISSUE THREAD

**Issue by BazZziliuS** [seanwlk/wfaccountmanager#4]
I found a problem with Russian authorization
If the account has mail.ru if there is two-factor authentication, then it outputs an error

```
Traceback (most recent call last):
  File "C:\Users\User\Documents\Testings\wfaccountmanager-0.0.7\staging.py", line 4, in <module>
    wf.login("LOGIN","PASSWORD")
  File "C:\Users\User\Documents\Testings\wfaccountmanager-0.0.7\wfaccountmanager\__init__.py", line 285, in login
    return _russia(account,password)
  File "C:\Users\User\Documents\Testings\wfaccountmanager-0.0.7\wfaccountmanager\__init__.py", line 181, in _russia
    _csrfMiddlewareToken = g.split("name=\"csrfmiddlewaretoken\" value=\"")[1].split('"')[0]
IndexError: list index out of range
[Finished in 3.1s]
```

_Yes I had to hide my username and password_

**Comment by seanwlk** [comment]
Tbh i never tried to add support for that and at the moment i do not have time to put in for this.
I quit the game years ago and just maintaining projects in my spare time.
Looking at your profile you seems to have programming knowledge, why don't you try to add the methods to handle mail run 2FA and PR? 😀

**Comment by BazZziliuS** [comment]
I'm just learning Python
Well, someday I'll try to do it.
Thanks for the answer :)
