### ISSUE TITLE
I suggest adding "Inventory"

### ISSUE THREAD

**Issue by BazZziliuS** [seanwlk/wfaccountmanager#7]
I suggest adding "Inventory" because many items are there, not in "Services"

Probably it will be useful...

![image](https://user-images.githubusercontent.com/18011884/185861011-2ed418de-d2c3-4739-98f1-08ae8ebf10c2.png)

**Comment by seanwlk** [comment]
I added the new Manager, you can `pip install -U git+https://github.com/seanwlk/wfaccountmanager` to install new version and try. Let me know if you have suggestions for this manager before i push a release on PyPi.

**Comment by BazZziliuS** [comment]
There are things and the history of translations, but it does not output information

```
Traceback (most recent call last):
  File "C:\Users\User\Documents\Testings\wfaccountmanager-0.0.7\staging.py", line 74, in <module>
    print(wf.myitems.history())
  File "C:\Users\User\Documents\Testings\wfaccountmanager-0.0.7\wfaccountmanager\__init__.py", line 596, in history
    r = self.accountManager.get(f'https://{self.accountManager._baseUrl}/dynamic/cart/?a=item_list_json')['history']
KeyError: 'history'
```
![image](https://user-images.githubusercontent.com/18011884/185897642-bd9ee8af-5d3e-46c1-9317-b02fd3de77e5.png)

Yes, and simply does not display a list of items in the inventory


`print(wf.myitems.getUserProfiles())`
```
Traceback (most recent call last):
  File "C:\Users\User\Documents\Testings\wfaccountmanager-0.0.7\staging.py", line 75, in <module>
    print(wf.myitems.getUserProfiles())
  File "C:\Users\User\Documents\Testings\wfaccountmanager-0.0.7\wfaccountmanager\__init__.py", line 579, in getUserProfiles
    r = self.accountManager.get(f'https://{self.accountManager._baseUrl}/dynamic/cart/?a=item_list_json')['user']
KeyError: 'user'
```

**Comment by seanwlk** [comment]
Checked that, apparently russian session is missing some cookie because it returns `{'reload': True}` instead of the data that international version returns. Will look for the missing cookie

**Comment by seanwlk** [comment]
Found it.
Apparently it's set via JS only in Russian version from here `https://wf.mail.ru/n.js` the two cookies are `n_js_t` and `n_js_d` where the first it's just the current unix timestamp and the second is some kind of calculation given from backend that results in a number which at the time i can't think of a way to implement since it uses a 2d canvas and does random stuff with it given a data image value.
